image: node:4.2.2

services:
  - mongo

variables:
  NODE_ENV: $(prod)

cache:
  paths:
    - code_is_HERE/ttcnpmcrawl/node_modules/

before_script:
    - npm install

all_tests:
  script:
   - nohup npm run start &
   - sleep 3
   - npm run test
