image: node:4.2.2

services:
  - mongo

variables:
  NODE_ENV: $(prod)

cache:
  paths:
    - code_is_HERE/ttcnpmcrawl/node_modules/

before_script:
    - cd code_is_HERE/ttcnpm/crawl && npm install

all_tests:
  script:
   - cd code_is_HERE/ttcnpm/crawl && nohup npm run start &
   - cd code_is_HERE/ttcnpm/crawl && sleep 3
   - cd code_is_HERE/ttcnpm/crawl && npm run test
