image: node:latest

services:
  - mongo

environment:
  NODE_ENV: $(prod)

cache:
  paths:
    - code_is_HERE/ttcnpmcrawl/node_modules/

before_script:
    - cd code_is_HERE/ttcnpmcrawl && npm install

all_tests:
  script:
   - cd code_is_HERE/ttcnpmcrawl && nohup npm run start &
   - cd code_is_HERE/ttcnpmcrawl && sleep 3
   - cd code_is_HERE/ttcnpmcrawl && npm run test
