image: node:latest

services:
  - mongo

cache:
  paths:
    - code_is_HERE/ttcnpmcrawl/node_modules/

before_script:
    - cd code_is_HERE/ttcnpmcrawl && npm install

all_tests:
  script:
   - cd nohup npm run start &
   - cd sleep 3
   - cd npm run test
