image: node:4.2.2

services:
  - mongodb

env:
  - NODE_ENV=prod PORT=80

cache:
  paths:
    - code_is_HERE/ttcnpmcrawl/node_modules

install:
  - npm install

all_tests:
  script:
   - nohup npm run start &
   - sleep 3
   - npm run test
