image: node:4.2.2

services:
  - mongodb

variables:
  NODE_ENV: $(prod)

cache:
  paths:
    - code_is_HERE/ttcnpmcrawl/node_modules

install:
  - npm install

all_tests:
  script:
   - nohup npm run start &
   - sleep 3
   - npm run test
