image: node:latest

services:
  - mongo

job:
  tags:
    - group-oisp-2-runner

variables:
  MONGO_URI: 'mongodb://127.0.0.1:27017/crawlTiki'
  NODE_ENV: 'dev'

cache:
  paths:
    - node_modules/

before_script:
    - cd code_is_HERE/ttcnpmcrawl && npm install

all_tests:
  script:
   - nohup npm run start &
   - sleep 3
   - npm run test
