image: node:latest

services:
  - mongo

variables:
  MONGO_URI: 'mongodb://127.0.0.1:27017/crawlTiki'
  NODE_ENV: 'dev'

before_script:
    - cd code_is_HERE/ttcnpmcrawl && npm install

all_tests:
  tags:
  - docker
  script:
   - nohup npm run start &
   - sleep 3
   - npm run test
  only:
    - tags
